### ISSUE TITLE
Scan: Could not get event CYCLE_ACTIVITY:CYCLES_LDM_PENDING

### ISSUE THREAD

**Issue by una-dinosauria** [technicolor-research/pq-fast-scan#1]
Hi! I get the following error when trying to run `./pqscan`

```
$ sudo ./pqscan
Scan: Could not get event CYCLE_ACTIVITY:CYCLES_LDM_PENDING
```

Any idea on what I could be doing wrong? I double-checked and I have libpfm4 installed.

**Comment by fandre90** [comment]
Hi,

It is likely that your processor does not support the `CYCLES_LDM_PENDING` performance event. Removing this event from the [events[] array](https://github.com/technicolor-research/pq-fast-scan/blob/master/pqscan/pqscan.cpp#L34) will fix this issue. You will also need to change the [event_count](https://github.com/technicolor-research/pq-fast-scan/blob/master/pqscan/pqscan.cpp#L40) variable accordingly.

Furthermore, to avoid any issues of this type, I would recommend keeping only the `"cycles"`, `"instructions"`, `"L1-dcache-loads"` and `"L1-dcache-load-misses"` events: 

```
static const char* events[] = { "cycles", "instructions", "L1-dcache-loads",
    "L1-dcache-load-misses"};
const int event_count = 4;
```

These events are supported on most processors (and they are also the most informative). If you want to display other events, you may use the `showevtinfo` program in libpfm-4.x.y/examples to see the full list of performance events supported by your processor. You can then add them to the events[] array.

Let me know if you run into any other issues

**Comment by una-dinosauria** [comment]
Thanks! that fixed it (:
